# Generated by Django 5.2.11 on 2026-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="available_times",
            field=models.JSONField(
                blank=True, default=list, verbose_name="زمان\u200cهای آزاد"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="levels",
            field=models.JSONField(blank=True, default=list, verbose_name="سطوح تدریس"),
        ),
    ]
